programa {
  inclua biblioteca Util-->u
  funcao inicio() {
    cadeia nome
    cadeia ir
    cadeia mexer
    cadeia final
    cadeia salvar
    inteiro opcao, entre, morrer
    real votosAfavor=2, votosContra=1
    cadeia junto

    escreva("Muito boa noite, jogador! Antes de começar, insira o nome do seu personagem: ") 
    leia(nome)
    escreva("\nCerto, ", nome, "!\n") 
    u.aguarde(1000)

    escreva("\nEm uma noite, você estava navegando pela internet buscando maneiras de ganhar dinheiro fácil, \ne uma proposta tentadora se mostra interessante, um Escape room com um prêmio no valor de R$100.000,00.\n") 
    u.aguarde(4000)

    escreva("\nA próxima campanha irá acontecer amanhã às 20h, em uma vila abandonada de São Paulo. Você vai? (sim/nao): ")
    leia(ir)
    se(ir=="nao"){
      escreva("\n🎉Você não se arriscou e sobreviveu!🎉\n")

    }senao{
      escreva("\n--NO DIA SEGUINTE--\n")
    u.aguarde(1000)

    escreva("\nEntrando em contato com os organizadores, você é instruído a ir para um prédio abandonado em uma área isolada adentrando a mata. \nO local é estranho. ",nome,", você tem certeza que quer ir?(sim/nao): ")
    leia(ir)
    se(ir=="nao"){
      escreva("\n🎉Você foi pra casa ileso!🎉\n")

   }senao{
     escreva("\nChegando na mata, a escuridão toma conta dos arredores, ruídos parecem vir de todos os lados, você sente uma presença entre as árvores. \nHá algo ali além de você?\n")
     u.aguarde(9000)

     escreva("\nAntes que você pudesse procurar aquilo que te perseguia, algo bate na sua cabeça... \n")
     u.aguarde(5000)

     escreva("\nApós horas inconsciente, você enfim acorda, olha ao redor e se percebe em uma sala com um design futurista, todas as paredes são feitas de aço, \nno canto esquerdo superior a uma televisão mais ao alto, na parede inferior há uma caixa grande fechada e a sua direita também \nhá uma caixa um pouco maior com um teclado e uma tela. Lá haviam mais 3 pessoas totalmente desconhecidas. \nApós minutos confusos, a tela se liga e uma voz é escutada por todos.\n")
     u.aguarde(22000)

     escreva("\n— Bem vindos, jogadores — Na tela a um estranho símbolo jamais visto por você, a pessoa falando é um idoso grisalho de barba comprida e bigode.") 
     u.aguarde(8000)

     escreva("\n— Vocês todos aqui, estão com um propósito, ganhar o prêmio no final.\n")
     u.aguarde(8000)
    limpa()

     escreva("\nVocê olha para os outros que estão na sala, um deles é um homem com uns 40 anos, 1,90 de altura, uma camisa xadrez verde clara e escura, \nbarba grisalha e várias cicatrizes pelo rosto.\n")
     u.aguarde(12000)

     escreva("\nA outra pessoa é uma mulher que aparenta ter 20 anos, 1,70 de altura, usa uma jaqueta preta, calças jeans e óculos de cor amarela \nnas lentes e armação preta que estão acima da cabeça.\n")
     u.aguarde(12000)

     escreva("\nE por último um garoto que parece mais novo, com uns 17 a 19 anos, mais ou menos 1,50 de altura, seus cabelos eram brancos \ne cacheados, usava um colete verde-escuro e calças pretas.\n")
     u.aguarde(12000)

    escreva("\n— Oque é isso? - O mais novo fala com a tv.\n")
     u.aguarde(5000)
    escreva("\n— Isso é oque todos vocês procuravam, o desafio do anfitrião — Quem quer que seja falando com vocês, ri enquanto segue falando. \n— Todos vocês aqui querem o mesmo, o prêmio e a glória de passar em um desafio tão ... memorável.\n")
     u.aguarde(10000)
    escreva("\n— Sequestraram a gente! - Grita o menino.\n")
     u.aguarde(5000)
    escreva("\n— Vocês aceitaram, foram até o lugar que pedimos, não fizemos nada com vocês - Rebate o velho.\n")
     u.aguarde(5000)
    escreva("\nA TV desliga.\n")
     u.aguarde(3000)
    escreva("\n— Que palhaçada — O homem mais velho reclama enquanto olha para a tv. — Se eu soubesse que isso iria acontecer, eu não viria!\n")
     u.aguarde(7000)
    escreva("\nA mulher anda pela sala e a analisa — É um “Escape room” não é, então é só achar as dicas e sair.\n")
     u.aguarde(7000)
    escreva("\n— É, então vamos ver o que temos — Ele começa a apontar pelos pontos de interesse pela sala. — Uma tela e um teclado \nem cima de uma caixa, uma tv, outra caixa e sei lá o que é isso, uma torre de tesla?\n")
     u.aguarde(10000)
    escreva("\nUma torre com um formato similar a um parafuso com leds em volta está perto da televisão.\n")
     u.aguarde(8000)
    limpa()

    escreva("\n— Não to entendendo nada, não tem lógica, são só itens aleatórios espalhados por aí!\n")
     u.aguarde(6000)
    escreva("\nO mais novo se aproxima da torre e toca.\n")
     u.aguarde(4000)
    escreva("\n— Aí merda!\n")
     u.aguarde(2000)
    escreva("\nUma dos leds acende.\n")
     u.aguarde(3000)
    escreva("\n— Eu levei um choque! - Diz o mais novo.\n")
     u.aguarde(5000)
    escreva("\n— Você tá bem Rubinho? - Perguntou o homem mais velho.\n")
     u.aguarde(6000)
    escreva("\n— To, sim, Johnny. \n")
     u.aguarde(3000)
    escreva("\n— Uma luz acendeu quando você tocou na torre — diz Johnny, apontando.\n")
     u.aguarde(5000)
    escreva("\n— Deixa eu ver — A mulher se aproxima e analisa, parecem ter muitos fios passando por dentro da torre. \n— Tem bastante energia passando por ali.\n")
     u.aguarde(7000)
    escreva("\n— É. Eu reparei, levei um choque!\n")
     u.aguarde(3000)
    escreva("\n— Tá, temos uma tela, um teclado, uma torre que dá choque — A moça observa a sala novamente. — E essa caixa.\n")
     u.aguarde(8000)
    escreva("\nEla anda em direção a caixa, parece um grande fogão com um local para passar algum tipo de cartão.\n")
     u.aguarde(8000)
    escreva("\n— Isso eu ainda não tinha visto — Os quatro participantes começam a se aproximar da caixa.\n")
     u.aguarde(7000)
    escreva("\nRubens olha em volta, e vê uma grande porta dupla e em cada lado dela um scanner para as mãos.\n")
     u.aguarde(7000)
    escreva("\n— Eba, mais uma coisa para olhar - Diz ele\n")
     u.aguarde(3000)
    escreva("\n— Esse jogo não vale o meu tempo e nem minha paciência, Rubens - Retruca Johnny.\n")
     u.aguarde(4000)
    escreva("\n— Para de reclamar Johnny!\n")
     u.aguarde(4000)
    limpa()

    escreva("\n— E vocês dois? Qual o nome de vocês, pirralhos? - Pergunta o mais velho.\n")
     u.aguarde(4000)
    escreva("\n— O meu é Erin, Erin Parker — Responde a mulher.\n")
     u.aguarde(4000)
    escreva("\n— Me chamo ",nome,".\n")
     u.aguarde(4000)
    escreva("\n— Eu sou Johnny Tabasco, e esse anãozinho é o Rubinho.\n")
     u.aguarde(4000)
    escreva("\n— Erin, que nome mais... diferente, sua mãe é bem criativa, já ",nome," é um nome bem sem sal - Fala o menor.\n")
     u.aguarde(5000)
    escreva("\nRubens começa a analisar o Scanner da esquerda.\n")
     u.aguarde(5000)
    escreva("\n— Parece que esse Scanner ta sem energia e tem... Parece um cabo solto. Erin! Olha o outro pra ver se tem energia.\n")
     u.aguarde(7000)
    escreva("\n— Deixa que eu vejo — Você anda até o outro Scanner e vê uma luz vermelha forte saindo de lá, tem energia.\n")
     u.aguarde(7000)
    escreva("\n— Aquela torre ta emitindo energia, e se por acaso nós fizéssemos uma corrente humana pra passar energia até o fio? - Diz Erin.\n")
     u.aguarde(9000)
    escreva("\n— É, pode funcionar, mas você disse que tem bastante energia passando por ali, e se quem ficar \nprimeiro morrer eletrocutado? - Pergunta Rubens.\n")
     u.aguarde(11000)
    escreva("\n— Tem razão, querem apostar no possível erro pessoal? - Erin pergunta para todos.\n")
     u.aguarde(6000)
    escreva("\n— Podemos tentar - Diz Johnny.\n")
     u.aguarde(4000)
    escreva("\n— Eu concordo - Resalta Erin.\n")
     u.aguarde(4000)
    escreva("\n— Acho melhor não, é muito arriscado - Rubinho afirma preocupado.\n")
     u.aguarde(5000)
    escreva("\n— E você? Ta todo caladão, o que você acha? - Johnny te pergunta.\n")
     u.aguarde(6000)
    limpa()
    
    escreva("\n1. Fazer a corrente humana.\n")
    escreva("2. Não, muito arriscado.")

    para(inteiro i=0; i<1; i++) {
    escreva("\nDigite o número equivalente a sua escolha: ")
    leia(opcao)} 

  escolha(opcao) {
    caso 1:
        votosAfavor++
        pare

    caso 2:
        votosContra++
        pare

    caso contrario:
        votosAfavor++
        pare
  }

  se(votosAfavor>votosContra){
    escreva("\n— Tá, vamos fazer isso, eu vou ficar pra encostar na torre - O mais velho afirma.\n")
    u.aguarde(6000)
    escreva("\n— Sabe que você pode morrer, não é?! - Rubinho ressalta.\n")
    u.aguarde(5000)
    escreva("\n— Prefiro que eu me machuque do que vocês.\n")
    u.aguarde(5000)
    escreva("\n— E eu quero apertar o outro Scan. — Erin avisa.\n")
    u.aguarde(4000)
    escreva("\n— Tá, vamos nessa - Diz Rubens.\n")
    u.aguarde(4000)
    escreva("\nJohnny se aproxima da torre e todos se organizam para designarem sua função.\n")
    u.aguarde(6000)
    escreva("\n— Rubens, se eu morrer, saia daqui vivo - Fala Johnny em tom protetor.\n")
    u.aguarde(6000)
    escreva("\n— Vai ficar tudo bem, tá? 1! - Rubinho começa.\n")
    u.aguarde(5000)
    escreva("\n— 2!\n")
    u.aguarde(1000)
    escreva("\n— 3!\n")
    u.aguarde(1000)
    escreva("\n— Vamos nessa! - Todos gritam!\n")
    u.aguarde(5000)
    escreva("\nJohnny encosta na torre e a energia passa pelo seu corpo, e por fim passa para o corpo de Rubens que coloca a mão no Scanner.\n")
    u.aguarde(7000)
    escreva("\n— Soltem! - Alerta Rubinho.\n")
    u.aguarde(3000)
    escreva("\nRubens solta a sua mão, e você sente a mão de Johnny não soltar a sua, sente a eletricidade passar por seu corpo, \nsente como se como um golpe dentro de você, sente seus músculos se contraírem violentamente.\n")
    u.aguarde(11000)
    escreva("\n(Pi!) Um dos leds se liga na torre.\n")
    u.aguarde(5000)
    escreva("\n— Soltem! -  Rubens botou a mão no scan junto de Erin e apenas uma pequena parte se abre.\n")
    u.aguarde(6000)
    escreva("\n(Pi!) Mais uma luz.\n")
    u.aguarde(4000)
    escreva("\nRubens corre na sua direção atirando se corpo contra o seu, isso faz com que a mão de Johnny solte a sua. \n")
    u.aguarde(6000)
    limpa()

    escreva("\n— Você está bem ",nome,"? - Erin te pergunta em meio ao caos.\n")
    u.aguarde(5000)
    escreva("\n— Johnny! - O mais novo grita em desespero\n")
    u.aguarde(5000)
    escreva("\nTodos os leds se acendem e um cartão salta da parte superior da torre.\n")
    u.aguarde(7000)
    escreva("\nA televisão se liga.\n")
    u.aguarde(4000)
    escreva("\n— Jogador, Johnny Tabasco eliminado.\n")
    u.aguarde(7000)
    escreva("\nO corpo de Johnny cheio de queimaduras cai ao lado esquerdo da torre.\n")
    u.aguarde(7000)
    escreva("\n— Não… Não! Não! Johnny! - Rubens se aproxima dele.\n")
    u.aguarde(5000)
    escreva("\n— Você tinha que ter... soltado!.\n")
    u.aguarde(5000)
    escreva("\nRubens começa a chorar incontrolavelmente.\n")
    u.aguarde(5000)
    escreva("\nErin se aproxima da torre.\n")
    u.aguarde(4000)
    escreva("\n— O cartão.\n")
    u.aguarde(4000)
    escreva("\nErin vai em direção a caixa grande e passa o cartão, (Ts!) a caixa se abre com uma densa fumaça saindo de dentro, \ndentro da caixa a um cabo HDMI, um cabo de força e 3 cabos de aço.\n")
    u.aguarde(12000)
    escreva("\n— Deve ser para o computador. — Erin começa a se aproximar com a caixa com tela e teclado. — Rubens, se sabe mex-\n")
    u.aguarde(8000)
    escreva("\n— Erin cala a boca! Meu amigo morreu!\n")
    u.aguarde(5000)
    escreva("\n— É, que triste, mas se ele morreu, nós também podemos morrer, e se essa sala tiver um tempo pra ser resolvida!\n")
    u.aguarde(10000)
    escreva("\nRubens está com o corpo de Johnny em seus braços.\n")
    u.aguarde(5000)
    escreva("\n— Eu não ligo!\n")
    u.aguarde(4000)
    limpa()

    escreva("\n— Você sabe mexer nessas coisas ",nome,"(sim/nao)?: \n")
    leia(mexer)
    se(mexer=="nao"){
    escreva("\n— E agora? Vou tentar conectar estes cabos — Erin vai para a parte de trás da caixa — Isso dever ser aqui, e...isso aqui.\n")
    u.aguarde(6000)
    escreva("\nA tela se liga e uma frase aparece.\n")
    u.aguarde(4000)
    }senao{
    escreva("\nVocê conecta os cabos, a tela se liga, na tela uma mensagem aparece.\n")
    u.aguarde(4000)
    }

    escreva("\ncA resposta está em suas mãos” Abaixo da frase a um espaço para algo ser escrito.\n")
    u.aguarde(4000)
    escreva("\n“— Oque? Só isso?! — Erin parece um pouco alterada. — Mais que… Merda! — Ela passa pela caixa, pega um cabo \ne se aproxima da televisão passando perto de Rubens e do corpo de Johnny.\n")
    u.aguarde(10000)
    escreva("\n— Seus babacas! — Erin começa a bater com o cabo sobre violentamente a televisão.\n")
    u.aguarde(8000)
    escreva("\nEnquanto bate em certo momento enquanto a tv está quase toda destruída, ela repara algo em sua mão.\n")
    u.aguarde(6000)
    escreva("\n—A... resposta. Está em suas mãos. — Erin vêm um número em sua mão. — 0811 é isso!\n")
    u.aguarde(8000)
    escreva("\nVocê se aproxima do computador e digita os números, (Tssss!) Mais uma parte da porta se abre.\n")
    u.aguarde(8000)
    escreva("\n— A porta! — Diz Erin animada e apontando.\n")
    u.aguarde(5000)
    escreva("\nMais uma frase aparece na tela “Você a ouve o tempo todo, mas nunca a vê. \nAinda assim, a resposta está atrás da sua própria escuta”\n")
    u.aguarde(8000)
    escreva("\n— Obvio, ouvido. — Rubens diz sem muita expressão e sem vontade.\n")
    u.aguarde(5000)
    escreva("\nErin se aproxima de você.\n")
    u.aguarde(3000)
    escreva("\n— Olha o meu ouvido.\n")
    u.aguarde(3000)
    escreva("\nNão há nada.\n")
    u.aguarde(3000)
    escreva("\nEla olha a sua orelha.\n")
    u.aguarde(4000)
    escreva("\n— 1803!\n")
    u.aguarde(3000)
    limpa()
    
    escreva("\nVocê digita e a porta se abre mais uma parte. Na tela, mais uma frase: “Para da sala escapar, tente se \nencontrar — a resposta está bem no centro do seu próprio olhar.”\n")
    u.aguarde(10000)
    escreva("\n— Olhos! — A mulher responde.\n")
    u.aguarde(5000)
    escreva("\n— Fecha os olhos ",nome,".\n")
    u.aguarde(5000)
    escreva("\nNão há nada.\n")
    u.aguarde(3000)
    escreva("\n— Feche os seus Erin! - Você diz.\n")
    u.aguarde(5000)
    escreva("\nTambém não há nada.\n")
    u.aguarde(4000)
    escreva("\n— Será que no Joh-\n")
    u.aguarde(3000)
    escreva("\n— Não tá nele, deve estar em mim. — Rubens rebate.\n")
    u.aguarde(5000)
    escreva("\nRubens fecha os olhos, no esquerdo a 08 e no direito 07.\n")
    u.aguarde(6000)
    escreva("\n— 0807! - Você fala.\n")
    u.aguarde(3000)
    escreva("\n— A porta! - Erin exclama novamente.\n")
    u.aguarde(3000)
    escreva("\nErin começa a sair da sala, porém para no momento que a tv se liga novamente mesmo destruída.\n")
    u.aguarde(6000)
    escreva("\n“Se alguém na sala ficar, as paredes e o chão vão começar a esquentar.”\n")
    u.aguarde(5000)
    escreva("\n— Vamos! - Erin chama todos.\n")
    u.aguarde(6000)
    escreva("\nVocê corre rápido e passa por Erin, quando ela vai acompanhar você Rubens avança para cima dela a atacando, \nRubens a pega desprevenida e a derruba no chão, começa a golpear o rosto dela a deixando inconsciente. \n")
    u.aguarde(10000)
    limpa()

    escreva("\n“10”\n")
    u.aguarde(2000)
    escreva("\nRubens começa a sair da sala correndo.\n")
    u.aguarde(4000)
    escreva("\n“9”\n")
    u.aguarde(2000)
    escreva("\nVocê quer tentar salvar a Erin?(sim/nao): \n")
    leia(salvar)

    se(salvar=="sim"){
    escreva("\nVocê corre o máximo que consegue.\n")
    u.aguarde(4000)
    escreva("\n“8”\n")
    u.aguarde(2000)
    escreva("\nVocê corre o máximo que consegue.\n")
    u.aguarde(4000)
    escreva("\nVocê tenta puxar o corpo de Erin com todas as suas forças.\n")
    u.aguarde(7000)
    escreva("\nEscolha um número entre 1 e 5: \n")
    leia(entre)

    se(entre==1 ou entre==3 ou entre==5){
    escreva("\nVocê puxa o corpo desacordado, tentando leva-lá até a sala, chegando perto.\n")
    u.aguarde(8000)
    escreva("\n“6”\n")
    u.aguarde(2000)
    escreva("\nVê Rubens de pé olhando para você se esforçando para levar o corpo de Erin.\n")
    u.aguarde(8000)
    escreva("\n“5”\n")
    u.aguarde(2000)
    escreva("\nErin começa acordar aos poucos, o calor é sufocante.\n")
    u.aguarde(8000)
    escreva("\n“4”\n")
    u.aguarde(2000)
    escreva("\n— Eu e você... nós podíamos ter passado juntos, mas você escolheu a coisa errada - Rubens diz. Como ele pode ser tão babaca?\n")
    u.aguarde(10000)
    escreva("\n“3”\n")
    u.aguarde(2000)
    escreva("\nRubens dá um chute em seu rosto e você cai para trás.\n")
    u.aguarde(5000)
    escreva("\n“2”\n")
    u.aguarde(2000)
    escreva("\n— Sinto muito - A voz de Rubens é a última coisa que você escuta.\n")
    u.aguarde(6000)
    escreva("\n“1”\n")
    u.aguarde(2000)
    escreva("\nAs portas se fecham lentamente.\n")
    u.aguarde(6000)
    escreva("\n“0”\n")
    u.aguarde(2000)
    escreva("\n— Jogadores ",nome," e Erin Parker, eliminados...\n")
    }senao{
      escreva("\nVocê não consegue salvá-la mesmo com todo o esforço. Seu corpo é tomado pelo calor torturante.\n")
      u.aguarde(6000)
      escreva("\n— Jogadores ",nome," e Erin Parker, eliminados...\n")
    }
    }senao{
    escreva("\nVocê e Rubens escutam a contagem chegar a zero e a porta se fechar.\n")
    u.aguarde(6000)
    escreva("\n— Jogadora Erin Parker eliminada.\n")
    u.aguarde(4000)
    escreva("\n— Escolheu o lado certo ",nome,"\n")
    u.aguarde(4000)
    escreva("\nAo analisar, a nova sala parece apenas um quadrado preto, seguindo a um corredor escuro com um chão quadriculado.\n")
    u.aguarde(7000)
    escreva("\n— Será que o chão é mais um jogo? - Rubens pergunta a você, que dá de ombros.\n")
    u.aguarde(5000)
    escreva("\nVocês pisam juntos no corredor, mas nada ocorre. Não é um jogo.\n")
    u.aguarde(4000)
    escreva("\nRubens começa a ir em direção ao final do corredor. Você vai junto?(sim/nao): \n")
    leia(junto)
    limpa()

    se(junto=="sim"){
    escreva("\nVocê começa a segui-lo, o corredor leva vocês a mais uma sala quadrada, no centro da sala há apenas uma torre \nde cimento pintada de preto que vai mais ou menos a sua cintura, em cima da torre \ntem uma caixa com oque parece um presente.\n")
    u.aguarde(10000)
    escreva("\n— Quer um presente? - Ele te entrega a caixa.\n")
    u.aguarde(5000)
    escreva("\nAo abrir você se depara com um revólver, nele a duas balas, atrás do revólver a um bilhete.\n")
    u.aguarde(5000)
    escreva("\n— Oque está escrito? - Rubinho pergunta.\n")
    u.aguarde(4000)
    escreva("\n—“ Parabéns, finalistas. Como pensamos em uma competição minimamente justa, pensamos em um final justo, \nvocês decidem que ganha no final.”\n")
    u.aguarde(9000)
    escreva("\n— Hum…\n")
    u.aguarde(3000)
    escreva("\nVocê vê um certo medo nos olhos de Rubens, e ele tenta pegar a arma em um momento que você se vê distraído.\n")
    u.aguarde(6000)
    escreva("\nRubens pega a arma antes de você, dá alguns passos para trás e aponta a arma para você.\n")
    u.aguarde(4000)
    escreva("\n— Parece que no final, o jogo não é tão justo.\n")
    u.aguarde(4000)
    escreva("\nEle aponta pra você. (TIC!) A arma não dispara.\n")
    u.aguarde(5000)
    escreva("\n— Merda! - Rubens reclama.\n")
    u.aguarde(4000)
    escreva("\nEscolha entre: \n")
    escreva("\n1. Tentar roubar a arma e tentar matar Rubens;")
    escreva("\nMorrer no lugar dele e encerrar o jogo.")
    escreva("O que você quer?(1/2: ")
    leia(morrer)

    se(morrer==1){
    escreva("\nVocê foi pra cima dele, em um movimento ágial arrancou a arma e atirou rapidamente.\n")
    u.aguarde(4000)
    escreva("\n— Jogador Rubens Naluto eliminado.\n")
    u.aguarde(4000)
    escreva("\n— Meus parabéns ",nome,",  você venceu o Escape Room do anfitrião.\n")
    u.aguarde(4000)
    escreva("\nAAAAHAHAHA GANHEI!\n")
    }senao{
      escreva("\nVocê aponta a arma para a sua própria cabeça e dispara,  sente um sopro, sente uma pressão em sua cabeça, \nsente como se você se desliga e o mundo apaga\n")
      u.aguarde(8000)
      escreva("\n— Jogador ",nome," eliminado.")
    }

    }senao{
      escreva("Você vê Rubens sumir na escuridão, um silêncio se instaura por alguns minutos. (POW!) \nVocê escuta o som de um disparo ecoar pelo corredor.")
      u.aguarde(9000)
      escreva("— Jogador Rubens Naluti eliminado.")
      u.aguarde(4000)
      escreva("\n— Meus parabéns ",nome,",  você venceu o Escape Room do anfitrião.\n")
      u.aguarde(4000)
      escreva("\nAAAAHAHAHA GANHEI!\n")
    }
    }

  }senao{
    escreva("\n— Concordo com ",nome," , pode não dar certo, acho melhor não fazermos isso, pode ser arriscado \ne um de nós pode se machucar. — A mulher opina.\n")
    u.aguarde(9000)
    escreva("\n— Tá, oque vamos fazer? — Rubens indaga.\n")
    u.aguarde(4000)
    escreva("\n— E se. . . nos recusarmos a jogar? — Johnny sugere.\n")
    u.aguarde(6000)
    escreva("\nErin se aproxima da televisão.\n")
    u.aguarde(3000)
    escreva("\n— Ei! Babacas!\n")
    u.aguarde(3000)
    escreva("\nA tv se liga.\n")
    u.aguarde(3000)
    escreva("\n— A gente quer parar de jogar!\n")
    u.aguarde(4000)
    escreva("\n— Infelizmente não será possível - O velho responde.\n")
    u.aguarde(5000)
    escreva("\n— Nós não vamos continuar essa loucura!\n")
    u.aguarde(4000)
    escreva("\n— Todos os jogadores estão de acordo em se recusarem a jogar? - A figura na TV pergunta a todos.\n")
    u.aguarde(4000)
    escreva("\n— Sim! — Rubens.\n")
    u.aguarde(3000)
    escreva("\n— Obvio! — Johnny.\n")
    u.aguarde(3000)
    escreva("\n— Obvio! — Johnny.\n")
    u.aguarde(3000)
    escreva("\n— Obvio! — Johnny.\n")
    u.aguarde(3000)
    escreva("\n— Sim - Erin.\n")
    u.aguarde(3000)
    escreva("\nVocê quer continuar?(sim/nao): \n")
    leia(final)

    se(final=="nao"){
    escreva("\n— A maioria está a favor de encerrar o jogo, então a finalização é imediata.\n")
    u.aguarde(5000)
    }senao{
      escreva("\n— Como todos estão de acordo, o jogo será finalizado.\n")
    u.aguarde(4000)
    }
    escreva("\nA sala começa a esquentar como um forno.\n")
    u.aguarde(4000)
    escreva("\n— Oque?! — Johnny exclama.\n")
    u.aguarde(3000)
    escreva("\n— Ai que merda! — Rubens grita.\n")
    u.aguarde(3000)
    escreva("\nVocê sente uma dor imediata que cresce a cada segundo que a sala aumenta sua temperatura, sente queimaduras \ne sua pele arder, sente suas forças se esvaindo e o ar ficando cada vez mais difícil de se respirar, e por fim, \nsente o mundo desaparecer e sua visão sumir por completo.\n")
    u.aguarde(8000)
    escreva("\n💀Você morreu💀\n")
  }
     }
    }
  }
}
